const MOD_SUPPORTED_QUERY_NAMES = [
  "anim_time",
  "anim_time_ticks",
  "anim_length",
  "delta_time",
  "loop_count",
  "key_frame_lerp_time",
  "life_time",
  "target_x_rotation",
  "target_y_rotation",
  "body_x_rotation",
  "body_y_rotation",
  "head_x_rotation",
  "head_y_rotation",
  "eye_target_x_rotation",
  "eye_target_y_rotation",
  "ground_speed",
  "vertical_speed",
  "modified_distance_moved",
  "walk_distance",
  "is_moving",
  "is_on_ground",
  "is_sneaking",
  "is_sprinting",
  "is_swimming",
  "is_gliding",
  "is_riding",
  "is_using_item",
  "is_sleeping",
  "is_emoting",
  "item_is_charged",
  "sleep_rotation",
  "is_on_fire",
  "is_in_water",
] as const;

export const PREVIEW_PLAYER_STATE_QUERIES: Readonly<Record<string, number>> = Object.fromEntries(
  MOD_SUPPORTED_QUERY_NAMES.flatMap((name) => [[`q.${name}`, 0], [`query.${name}`, 0]]),
);
