import { unzipSync } from "fflate";
import type { BlockStateData, DisplayNbtPatch, ItemStackData } from "../../domain/minecraftData";
import type { Matrix16 } from "../../domain/matrix";
import { readBlockState, readDisplayNbt, readItemStack } from "../../format/minecraftData";
import { asMatrix16 } from "../../format/matrix";
import { requireAnimationDurationTicks } from "../../format/time";
import {
  findMatchingSnbtDelimiter,
  omitSnbtFields,
  parseSnbtCompound,
  readSnbtRawField,
  readSnbtStringField,
  serializeSnbtCompound,
  splitSnbtTopLevel,
} from "../../format/snbt";
import type { ImportInput } from "../adapter";
import { cachedInputValue } from "../common/inputCache";

const decoder = new TextDecoder();
const TICKS_PER_BD_FRAME = 2;
const MAX_ARCHIVE_ENTRY_BYTES = 64 * 1024 * 1024;
const CREATE_PATH = /^data\/([^/]+)\/functions?\/_\/create\.mcfunction$/;
const KEYFRAME_PATH = /^data\/([^/]+)\/functions?\/k\/([^/]+)\/keyframe_(\d+)\.mcfunction$/;
const OWNED_DISPLAY_FIELDS = new Set([
  "id", "Tags", "Passengers", "transformation", "interpolation_duration", "start_interpolation",
  "item", "item_display", "block_state", "text",
]);

interface BdDatapackArchive {
  files: Map<string, string>;
  namespace: string;
  createPath: string;
}

interface BdSourceDisplayBase {
  id: string;
  tag: string;
  defaultMatrix: Matrix16;
  entityNbt?: string;
  initialPayload: string;
}

export type BdSourceDisplay =
  | (BdSourceDisplayBase & { type: "item_display"; itemStack: ItemStackData; itemDisplay: string })
  | (BdSourceDisplayBase & { type: "block_display"; blockState: BlockStateData })
  | (BdSourceDisplayBase & { type: "text_display"; text: unknown });

export interface BdSourceTransformFrame {
  tick: number;
  matrix: Matrix16;
  interpolation: { type: "step" } | { type: "linear"; durationTicks: number };
}

export interface BdSourceNbtFrame {
  tick: number;
  value: DisplayNbtPatch;
}

export interface BdSourceAnimation {
  name: string;
  durationTicks: number;
  transforms: Record<string, BdSourceTransformFrame[]>;
  nbt: Record<string, BdSourceNbtFrame[]>;
}

export interface BdDatapackSource {
  namespace: string;
  displays: BdSourceDisplay[];
  animations: BdSourceAnimation[];
  droppedCamera: boolean;
}

export function readBdDatapackSource(input: ImportInput): BdDatapackSource {
  return cachedInputValue(input, "bd_datapack_source", () => {
    const archive = readArchive(input);
    const displays = readDisplays(archive.files.get(archive.createPath)!, archive.namespace);
    const projected = readAnimations(archive, displays);
    if (projected.animations.length === 0) throw new Error("BD Engine datapack does not contain animation keyframes.");
    return { namespace: archive.namespace, displays, ...projected };
  });
}

function readArchive(input: ImportInput): BdDatapackArchive {
  if (!hasZipHeader(input.bytes)) throw new Error("BD Engine datapack is not a ZIP archive.");
  const files = new Map<string, string>();
  let entries: Record<string, Uint8Array>;
  try {
    entries = unzipSync(input.bytes, {
      filter: (entry) => entry.originalSize <= MAX_ARCHIVE_ENTRY_BYTES
        && (entry.name === "pack.mcmeta" || CREATE_PATH.test(entry.name) || KEYFRAME_PATH.test(entry.name)),
    });
  } catch (error) {
    throw new Error("BD Engine datapack ZIP could not be read.", { cause: error });
  }
  for (const [path, bytes] of Object.entries(entries)) files.set(path.replaceAll("\\", "/"), decoder.decode(bytes));
  const creates = [...files.keys()].flatMap((path) => {
    const match = CREATE_PATH.exec(path);
    return match ? [{ path, namespace: match[1] }] : [];
  });
  if (creates.length !== 1) throw new Error(`BD Engine datapack must contain exactly one create function; found ${creates.length}.`);
  const create = creates[0];
  if (!files.get(create.path)?.includes("Project created via BDEngine")) {
    throw new Error("Datapack create function was not generated by BD Engine.");
  }
  if (![...files.keys()].some((path) => KEYFRAME_PATH.test(path))) {
    throw new Error("BD Engine datapack does not contain keyframes.");
  }
  return { files, namespace: create.namespace, createPath: create.path };
}

function hasZipHeader(bytes: Uint8Array): boolean {
  return bytes.length >= 4 && bytes[0] === 0x50 && bytes[1] === 0x4b
    && ((bytes[2] === 0x03 && bytes[3] === 0x04) || (bytes[2] === 0x05 && bytes[3] === 0x06));
}

function readDisplays(createFunction: string, namespace: string): BdSourceDisplay[] {
  const found: { index: number; display: BdSourceDisplay }[] = [];
  const entityStart = /\{\s*id\s*:\s*["'](?:minecraft:)?(item_display|block_display|text_display)["']/g;
  for (const match of createFunction.matchAll(entityStart)) {
    const start = match.index!;
    const end = findMatchingSnbtDelimiter(createFunction, start, "{", "}");
    const compound = createFunction.slice(start, end + 1);
    const tag = readStringList(readSnbtRawField(compound, "Tags"))
      .find((value) => new RegExp(`^${escapeRegExp(namespace)}_(\\d+)$`).test(value));
    if (!tag) continue;
    const index = Number(new RegExp(`^${escapeRegExp(namespace)}_(\\d+)$`).exec(tag)![1]);
    const display = readDisplay(`display_${index}`, tag, match[1], compound);
    found.push({ index, display });
  }
  found.sort((first, second) => first.index - second.index);
  if (found.length === 0) throw new Error("BD Engine datapack create function does not contain display nodes.");
  const tags = new Set<string>();
  for (const { display } of found) {
    if (tags.has(display.tag)) throw new Error(`BD Engine datapack contains duplicate display tag ${display.tag}.`);
    tags.add(display.tag);
  }
  return found.map(({ display }) => display);
}

function readDisplay(id: string, tag: string, type: string, compound: string): BdSourceDisplay {
  const defaultMatrix = readMatrix(readSnbtRawField(compound, "transformation"), `${id} create transformation`);
  const entityNbt = omitSnbtFields(compound, OWNED_DISPLAY_FIELDS);
  const common = { id, tag, defaultMatrix, ...(entityNbt ? { entityNbt } : {}) };
  if (type === "item_display") {
    const item = readSnbtRawField(compound, "item");
    if (!item) throw new Error(`BD Engine datapack node ${id} does not contain an item.`);
    return {
      ...common,
      type: "item_display",
      initialPayload: item,
      itemStack: readItemStack(item),
      itemDisplay: readSnbtStringField(compound, "item_display") ?? readBareField(compound, "item_display") ?? "none",
    };
  }
  if (type === "block_display") {
    const blockState = readSnbtRawField(compound, "block_state");
    if (!blockState) throw new Error(`BD Engine datapack node ${id} does not contain block_state.`);
    return { ...common, type: "block_display", initialPayload: blockState, blockState: readBlockState(blockState) };
  }
  const rawText = readSnbtRawField(compound, "text");
  if (!rawText) throw new Error(`BD Engine datapack node ${id} does not contain text.`);
  const text = readSnbtStringField(compound, "text") ?? readBareField(compound, "text") ?? "";
  return { ...common, type: "text_display", initialPayload: rawText, text: parseText(text) };
}

function readAnimations(
  archive: BdDatapackArchive,
  displays: readonly BdSourceDisplay[],
): Pick<BdDatapackSource, "animations" | "droppedCamera"> {
  const grouped = new Map<string, { index: number; path: string; content: string }[]>();
  for (const [path, content] of archive.files) {
    const match = KEYFRAME_PATH.exec(path);
    if (!match || match[1] !== archive.namespace) continue;
    const frames = grouped.get(match[2]) ?? [];
    frames.push({ index: Number(match[3]), path, content });
    grouped.set(match[2], frames);
  }
  const displayByTag = new Map(displays.map((display) => [display.tag, display]));
  let droppedCamera = false;
  const animations = [...grouped.entries()].sort(([first], [second]) => first.localeCompare(second)).map(([name, frames]) => {
    frames.sort((first, second) => first.index - second.index);
    frames.forEach((frame, expected) => {
      if (frame.index !== expected) throw new Error(`BD Engine animation ${name} is missing keyframe_${expected}.mcfunction.`);
    });
    const transforms = Object.fromEntries(displays.map((display) => [display.id, [] as BdSourceTransformFrame[]]));
    const nbt = Object.fromEntries(displays.map((display) => [display.id, [] as BdSourceNbtFrame[]]));
    const currentPayloadByTag = new Map(displays.map((display) => [display.tag, display.initialPayload]));
    for (const frame of frames) {
      const lines = frame.content.split(/\r?\n/).map((value) => value.trim()).filter(Boolean);
      for (const line of lines) {
        if (line.startsWith("#") || line.startsWith("schedule function ")) continue;
        if (line.includes(`tag=${archive.namespace}_camera`)) {
          droppedCamera = true;
          continue;
        }
        const merge = /^data merge entity @e\[([^\]]+)]\s+(\{.*})$/.exec(line);
        if (!merge) throw new Error(`Unsupported command in ${frame.path}: ${line}`);
        const tag = /(?:^|,)tag=([^,\]]+)/.exec(merge[1])?.[1];
        const display = tag ? displayByTag.get(tag) : undefined;
        if (!tag || !display) throw new Error(`Keyframe ${frame.path} targets an unknown display tag: ${tag ?? "<missing>"}`);
        validateDisplayMerge(display, merge[2], frame.path);
        const payloadUpdate = readDisplayPayloadUpdate(display, merge[2]);
        if (!payloadUpdate) continue;
        const mergedPayload = mergeSnbtValue(currentPayloadByTag.get(tag)!, payloadUpdate);
        setNbtFrame(nbt[display.id], frame.index * TICKS_PER_BD_FRAME, display, display.initialPayload, mergedPayload);
        currentPayloadByTag.set(tag, mergedPayload);
      }
      for (const line of lines) {
        if (line.startsWith("#") || line.startsWith("schedule function ") || line.includes(`tag=${archive.namespace}_camera`)) continue;
        const merge = /^data merge entity @e\[([^\]]+)]\s+(\{.*})$/.exec(line)!;
        const matrix = readSnbtRawField(merge[2], "transformation");
        if (!matrix) continue;
        const tag = /(?:^|,)tag=([^,\]]+)/.exec(merge[1])?.[1];
        const display = tag ? displayByTag.get(tag) : undefined;
        if (!display) throw new Error(`Keyframe ${frame.path} targets an unknown display tag: ${tag ?? "<missing>"}`);
        const duration = readIntegerField(merge[2], "interpolation_duration", 0);
        transforms[display.id].push({
          tick: frame.index * TICKS_PER_BD_FRAME,
          matrix: readMatrix(matrix, `${frame.path} ${display.id} transformation`),
          interpolation: duration === 0 ? { type: "step" } : { type: "linear", durationTicks: duration },
        });
      }
    }
    return {
      name,
      durationTicks: requireAnimationDurationTicks(frames.length * TICKS_PER_BD_FRAME, `${name} duration`),
      transforms,
      nbt,
    };
  });
  return { animations, droppedCamera };
}

function validateDisplayMerge(display: BdSourceDisplay, compound: string, path: string): void {
  const allowed = new Set(["transformation", "interpolation_duration", "start_interpolation"]);
  if (display.type === "item_display") allowed.add("item");
  else if (display.type === "block_display") allowed.add("block_state");
  else allowed.add("text");
  const unsupported = parseSnbtCompound(compound).find((field) => !allowed.has(field.name));
  if (unsupported) throw new Error(`Unsupported display data field ${unsupported.name} in ${path}.`);
}

function readDisplayPayloadUpdate(display: BdSourceDisplay, compound: string): string | null {
  if (display.type === "item_display") return readSnbtRawField(compound, "item");
  if (display.type === "block_display") return readSnbtRawField(compound, "block_state");
  return readSnbtRawField(compound, "text");
}

function setNbtFrame(frames: BdSourceNbtFrame[], tick: number, display: BdSourceDisplay, initialPayload: string, payload: string): void {
  if (frames.length === 0) frames.push({ tick: 0, value: readDisplayNbt(displayPayloadNbt(display, initialPayload)) });
  const frame = { tick, value: readDisplayNbt(displayPayloadNbt(display, payload)) };
  if (frames.at(-1)!.tick === tick) frames[frames.length - 1] = frame;
  else frames.push(frame);
}

function displayPayloadNbt(display: BdSourceDisplay, payload: string): string {
  if (display.type === "item_display") return serializeSnbtCompound([["item", payload]]);
  if (display.type === "block_display") return serializeSnbtCompound([["block_state", payload]]);
  return serializeSnbtCompound([["text", payload]]);
}

function mergeSnbtValue(current: string, update: string): string {
  if (!current.startsWith("{") || !current.endsWith("}") || !update.startsWith("{") || !update.endsWith("}")) return update;
  const fields = new Map(parseSnbtCompound(current).map((field) => [field.name, field.value]));
  for (const field of parseSnbtCompound(update)) {
    const previous = fields.get(field.name);
    fields.set(field.name, previous ? mergeSnbtValue(previous, field.value) : field.value);
  }
  return serializeSnbtCompound(fields);
}

function readMatrix(raw: string | null, label: string): Matrix16 {
  if (!raw?.startsWith("[") || !raw.endsWith("]")) throw new Error(`${label} must be an SNBT list.`);
  return asMatrix16(splitSnbtTopLevel(raw.slice(1, -1)).map((value) => {
    const parsed = Number(value.replace(/[bBsSlLfFdD]$/, ""));
    if (!Number.isFinite(parsed)) throw new Error(`${label} contains an invalid number: ${value}`);
    return parsed;
  }), label);
}

function readStringList(raw: string | null): string[] {
  if (!raw?.startsWith("[") || !raw.endsWith("]")) return [];
  return splitSnbtTopLevel(raw.slice(1, -1)).flatMap((value) => {
    try {
      const parsed = JSON.parse(value) as unknown;
      return typeof parsed === "string" ? [parsed] : [];
    } catch {
      return value.startsWith("'") && value.endsWith("'") ? [value.slice(1, -1)] : [];
    }
  });
}

function readBareField(compound: string, name: string): string | null {
  const raw = readSnbtRawField(compound, name);
  return raw && /^[A-Za-z0-9._+-]+$/.test(raw) ? raw : null;
}

function readIntegerField(compound: string, name: string, fallback: number): number {
  const raw = readSnbtRawField(compound, name);
  if (raw == null) return fallback;
  const value = Number(raw.replace(/[bBsSlL]$/, ""));
  if (!Number.isInteger(value) || value < 0) throw new Error(`${name} must be a non-negative integer.`);
  return value;
}

function parseText(value: string): unknown {
  try { return JSON.parse(value) as unknown; } catch { return { text: value }; }
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
