import { unzipSync } from "fflate";
import type { Matrix16 } from "../../format/emoteAnimation";
import { asMatrix16 } from "../../format/matrix";
import { sanitizeResourcePath } from "../../format/resourceLocation";
import {
  findMatchingSnbtDelimiter,
  omitSnbtFields,
  parseSnbtCompound,
  readSnbtRawField,
  readSnbtStringField,
  serializeSnbtCompound,
  splitSnbtTopLevel,
} from "../../format/snbt";
import type { ImportAdapter, ImportInput, ProbeResult } from "../adapter";
import { cachedInputValue } from "../inputCache";
import type { ImportedAnimation, ImportedNode, ImportedNodeTrack, ImportedProject } from "../types";

const decoder = new TextDecoder();
const TICKS_PER_BD_FRAME = 2;
const MAX_ARCHIVE_ENTRY_BYTES = 64 * 1024 * 1024;
const CREATE_PATH = /^data\/([^/]+)\/functions?\/_\/create\.mcfunction$/;
const KEYFRAME_PATH = /^data\/([^/]+)\/functions?\/k\/([^/]+)\/keyframe_(\d+)\.mcfunction$/;
const OWNED_DISPLAY_FIELDS = new Set([
  "id", "Tags", "Passengers", "transformation", "interpolation_duration", "start_interpolation",
  "item", "item_display", "block_state", "text",
]);

interface BdDatapackArchive {
  files: Map<string, string>;
  namespace: string;
  createPath: string;
}

interface ImportedDisplays {
  nodes: Record<string, ImportedNode>;
  nodeIdsByTag: Map<string, string>;
  nodeIdsByTagAndPayload: Map<string, Map<string, string>>;
  nodeIdsByTagInOrder: Map<string, string[]>;
  payloadByNodeId: Map<string, string>;
}

export const bdDatapackAdapter: ImportAdapter = {
  id: "bd_datapack",
  label: "BD Engine datapack",
  extensions: ["zip"],

  probe(input: ImportInput): ProbeResult {
    if (!hasZipHeader(input.bytes)) return { confidence: 0, reason: "not a ZIP archive" };
    try {
      readArchive(input);
      return { confidence: 100, reason: "contains a BD Engine create function and animation keyframes" };
    } catch {
      return { confidence: 0, reason: "not a BD Engine datapack" };
    }
  },

  async import(input: ImportInput): Promise<ImportedProject> {
    const archive = readArchive(input);
    const createFunction = archive.files.get(archive.createPath)!;
    const displays = importDisplays(createFunction, archive.namespace);
    const diagnostics: ImportedProject["diagnostics"] = [];
    const animations = importAnimations(archive, displays, diagnostics);
    if (animations.length === 0) throw new Error("BD Engine datapack does not contain animation keyframes.");
    const name = prettify(archive.namespace);
    return {
      source: "bd_datapack",
      sourceName: input.name,
      suggestedMetadata: { name, description: `${name} emote.`, hide_player: true },
      suggestedNamespace: archive.namespace,
      nodes: displays.nodes,
      animations,
      diagnostics,
      artifacts: new Map(),
    };
  },
};

function readArchive(input: ImportInput): BdDatapackArchive {
  return cachedInputValue(input, "bd_datapack_zip", () => {
    if (!hasZipHeader(input.bytes)) throw new Error("BD Engine datapack is not a ZIP archive.");
    const files = new Map<string, string>();
    let entries: Record<string, Uint8Array>;
    try {
      entries = unzipSync(input.bytes, {
        filter: (entry) => entry.originalSize <= MAX_ARCHIVE_ENTRY_BYTES
          && (entry.name === "pack.mcmeta" || CREATE_PATH.test(entry.name) || KEYFRAME_PATH.test(entry.name)),
      });
    } catch (error) {
      throw new Error("BD Engine datapack ZIP could not be read.", { cause: error });
    }
    for (const [path, bytes] of Object.entries(entries)) files.set(path.replaceAll("\\", "/"), decoder.decode(bytes));
    const creates = [...files.keys()].flatMap((path) => {
      const match = CREATE_PATH.exec(path);
      return match ? [{ path, namespace: match[1] }] : [];
    });
    if (creates.length !== 1) throw new Error(`BD Engine datapack must contain exactly one create function; found ${creates.length}.`);
    const create = creates[0];
    if (!files.get(create.path)?.includes("Project created via BDEngine")) {
      throw new Error("Datapack create function was not generated by BD Engine.");
    }
    if (![...files.keys()].some((path) => KEYFRAME_PATH.test(path))) {
      throw new Error("BD Engine datapack does not contain keyframes.");
    }
    return { files, namespace: create.namespace, createPath: create.path };
  });
}

function hasZipHeader(bytes: Uint8Array): boolean {
  return bytes.length >= 4 && bytes[0] === 0x50 && bytes[1] === 0x4b
    && ((bytes[2] === 0x03 && bytes[3] === 0x04) || (bytes[2] === 0x05 && bytes[3] === 0x06));
}

function importDisplays(createFunction: string, namespace: string): ImportedDisplays {
  const found: { index: number; tag: string; node: ImportedNode }[] = [];
  const entityStart = /\{\s*id\s*:\s*["'](?:minecraft:)?(item_display|block_display|text_display)["']/g;
  for (const match of createFunction.matchAll(entityStart)) {
    const start = match.index!;
    const end = findMatchingSnbtDelimiter(createFunction, start, "{", "}");
    const compound = createFunction.slice(start, end + 1);
    const tag = readStringList(readSnbtRawField(compound, "Tags"))
      .find((value) => new RegExp(`^${escapeRegExp(namespace)}_(\\d+)$`).test(value));
    if (!tag) continue;
    const index = Number(new RegExp(`^${escapeRegExp(namespace)}_(\\d+)$`).exec(tag)![1]);
    found.push({ index, tag, node: importDisplay(`display_${index}`, match[1], compound) });
  }
  found.sort((first, second) => first.index - second.index);
  if (found.length === 0) throw new Error("BD Engine datapack create function does not contain display nodes.");
  const tags = new Set<string>();
  for (const display of found) {
    if (tags.has(display.tag)) throw new Error(`BD Engine datapack contains duplicate display tag ${display.tag}.`);
    tags.add(display.tag);
  }
  const nodes = Object.fromEntries(found.map((display) => [display.node.id, display.node]));
  const nodeIdsByTag = new Map(found.map((display) => [display.tag, display.node.id]));
  const payloadByNodeId = new Map(found.map((display) => [display.node.id, displayPayload(display.node)]));
  return {
    nodes,
    nodeIdsByTag,
    payloadByNodeId,
    nodeIdsByTagAndPayload: new Map(found.map((display) => [
      display.tag,
      new Map([[payloadByNodeId.get(display.node.id)!, display.node.id]]),
    ])),
    nodeIdsByTagInOrder: new Map(found.map((display) => [display.tag, [display.node.id]])),
  };
}

function importDisplay(id: string, type: string, compound: string): ImportedNode {
  const defaultMatrix = readMatrix(readSnbtRawField(compound, "transformation"), `${id} create transformation`);
  const entityNbt = omitSnbtFields(compound, OWNED_DISPLAY_FIELDS);
  const common = { id, defaultMatrix, visible: true, ...(entityNbt ? { entityNbt } : {}) };
  if (type === "item_display") {
    const item = readSnbtRawField(compound, "item");
    if (!item) throw new Error(`BD Engine datapack node ${id} does not contain an item.`);
    return {
      ...common,
      type: "item_display",
      itemStackSnbt: item,
      itemDisplay: readSnbtStringField(compound, "item_display") ?? readBareField(compound, "item_display") ?? "none",
    };
  }
  if (type === "block_display") {
    const blockState = readSnbtRawField(compound, "block_state");
    if (!blockState) throw new Error(`BD Engine datapack node ${id} does not contain block_state.`);
    return { ...common, type: "block_display", blockStateSnbt: blockState };
  }
  const text = readSnbtStringField(compound, "text") ?? readBareField(compound, "text") ?? "";
  return { ...common, type: "text_display", text: parseText(text) };
}

function importAnimations(
  archive: BdDatapackArchive,
  displays: ImportedDisplays,
  diagnostics: ImportedProject["diagnostics"],
): ImportedAnimation[] {
  const grouped = new Map<string, { index: number; path: string; content: string }[]>();
  for (const [path, content] of archive.files) {
    const match = KEYFRAME_PATH.exec(path);
    if (!match || match[1] !== archive.namespace) continue;
    const frames = grouped.get(match[2]) ?? [];
    frames.push({ index: Number(match[3]), path, content });
    grouped.set(match[2], frames);
  }
  let droppedCamera = false;
  const animations = [...grouped.entries()].sort(([first], [second]) => first.localeCompare(second)).map(([animationName, frames]) => {
    frames.sort((first, second) => first.index - second.index);
    frames.forEach((frame, expected) => {
      if (frame.index !== expected) throw new Error(`BD Engine animation ${animationName} is missing keyframe_${expected}.mcfunction.`);
    });
    const tracks: Record<string, ImportedNodeTrack> = Object.fromEntries(
      Object.keys(displays.nodes).map((id) => [id, { transforms: [], visibility: [] }]),
    );
    const activeNodeByTag = new Map(displays.nodeIdsByTag);
    const currentPayloadByTag = new Map([...displays.nodeIdsByTag].map(([tag, nodeId]) => [tag, displays.payloadByNodeId.get(nodeId)!]));
    for (const frame of frames) {
      const lines = frame.content.split(/\r?\n/).map((value) => value.trim()).filter(Boolean);
      for (const line of lines) {
        if (line.startsWith("#") || line.startsWith("schedule function ")) continue;
        if (line.includes(`tag=${archive.namespace}_camera`)) {
          droppedCamera = true;
          continue;
        }
        const merge = /^data merge entity @e\[([^\]]+)]\s+(\{.*})$/.exec(line);
        if (!merge) throw new Error(`Unsupported command in ${frame.path}: ${line}`);
        const tag = /(?:^|,)tag=([^,\]]+)/.exec(merge[1])?.[1];
        const baseNodeId = tag ? displays.nodeIdsByTag.get(tag) : undefined;
        if (!tag || !baseNodeId) throw new Error(`Keyframe ${frame.path} targets an unknown display tag: ${tag ?? "<missing>"}`);
        validateDisplayMerge(displays.nodes[baseNodeId], merge[2], frame.path);
        const payloadUpdate = readDisplayPayloadUpdate(displays.nodes[baseNodeId], merge[2]);
        if (!payloadUpdate) continue;
        const previousNodeId = activeNodeByTag.get(tag)!;
        const mergedPayload = mergeSnbtValue(currentPayloadByTag.get(tag)!, payloadUpdate);
        const activeNodeId = ensurePayloadVariant(displays, tag, baseNodeId, mergedPayload);
        if (!tracks[activeNodeId]) tracks[activeNodeId] = {
          transforms: tracks[baseNodeId].transforms.map((transform) => ({ ...transform })),
          visibility: [],
        };
        if (activeNodeId !== previousNodeId) {
          tracks[previousNodeId].visibility.push({ tick: frame.index * TICKS_PER_BD_FRAME, visible: false });
          tracks[activeNodeId].visibility.push({ tick: frame.index * TICKS_PER_BD_FRAME, visible: true });
          activeNodeByTag.set(tag, activeNodeId);
        }
        currentPayloadByTag.set(tag, mergedPayload);
      }
      for (const line of lines) {
        if (line.startsWith("#") || line.startsWith("schedule function ") || line.includes(`tag=${archive.namespace}_camera`)) continue;
        const merge = /^data merge entity @e\[([^\]]+)]\s+(\{.*})$/.exec(line)!;
        const matrix = readSnbtRawField(merge[2], "transformation");
        if (!matrix) continue;
        const tag = /(?:^|,)tag=([^,\]]+)/.exec(merge[1])?.[1];
        const nodeIds = tag ? displays.nodeIdsByTagInOrder.get(tag) : undefined;
        if (!nodeIds) throw new Error(`Keyframe ${frame.path} targets an unknown display tag: ${tag ?? "<missing>"}`);
        const duration = readIntegerField(merge[2], "interpolation_duration", 0);
        for (const nodeId of nodeIds) {
          if (!tracks[nodeId]) tracks[nodeId] = { transforms: [], visibility: [] };
          tracks[nodeId].transforms.push({
            tick: frame.index * TICKS_PER_BD_FRAME,
            matrix: readMatrix(matrix, `${frame.path} ${nodeId} transformation`),
            interpolation: duration === 0 ? { type: "step" } : { type: "linear", durationTicks: duration },
          });
        }
      }
    }
    return {
      id: sanitizeResourcePath(animationName, "default"),
      name: prettify(animationName),
      durationTicks: frames.length * TICKS_PER_BD_FRAME,
      loop: "loop" as const,
      loopDelayTicks: 0,
      tracks,
      events: { start: [], timeline: [], loop: [], stop: [] },
    };
  });
  if (droppedCamera) diagnostics.push({
    severity: "warning",
    code: "bd_datapack_camera_ignored",
    message: "BD Engine camera movement is not part of the emote format and was ignored.",
    sourcePath: "data/*/function/k/*/keyframe_*.mcfunction",
  });
  return animations;
}

function validateDisplayMerge(node: ImportedNode, compound: string, path: string): void {
  const allowed = new Set(["transformation", "interpolation_duration", "start_interpolation"]);
  if (node.type === "item_display") allowed.add("item");
  else if (node.type === "block_display") allowed.add("block_state");
  else if (node.type === "text_display") allowed.add("text");
  const unsupported = parseSnbtCompound(compound).find((field) => !allowed.has(field.name));
  if (unsupported) throw new Error(`Unsupported display data field ${unsupported.name} in ${path}.`);
}

function readDisplayPayloadUpdate(node: ImportedNode, compound: string): string | null {
  if (node.type === "item_display") return readSnbtRawField(compound, "item");
  if (node.type === "block_display") return readSnbtRawField(compound, "block_state");
  if (node.type === "text_display") return readSnbtRawField(compound, "text");
  return null;
}

function ensurePayloadVariant(displays: ImportedDisplays, tag: string, baseNodeId: string, payload: string): string {
  const variants = displays.nodeIdsByTagAndPayload.get(tag)!;
  const existing = variants.get(payload);
  if (existing) return existing;
  const base = displays.nodes[baseNodeId];
  const index = variants.size;
  const id = `${baseNodeId}_variant_${index}`;
  const node = withDisplayPayload(base, id, payload);
  displays.nodes[id] = node;
  displays.payloadByNodeId.set(id, payload);
  displays.nodeIdsByTagInOrder.get(tag)!.push(id);
  variants.set(payload, id);
  return id;
}

function displayPayload(node: ImportedNode): string {
  if (node.type === "item_display") return node.itemStackSnbt;
  if (node.type === "block_display") return node.blockStateSnbt;
  if (node.type === "text_display") return JSON.stringify(node.text);
  throw new Error(`Node ${node.id} is not a display.`);
}

function withDisplayPayload(base: ImportedNode, id: string, payload: string): ImportedNode {
  if (base.type === "item_display") return { ...base, id, visible: false, itemStackSnbt: payload };
  if (base.type === "block_display") return { ...base, id, visible: false, blockStateSnbt: payload };
  if (base.type === "text_display") {
    const value = readSnbtString(payload) ?? payload;
    return { ...base, id, visible: false, text: parseText(value) };
  }
  throw new Error(`Node ${base.id} is not a display.`);
}

function mergeSnbtValue(current: string, update: string): string {
  if (!current.startsWith("{") || !current.endsWith("}") || !update.startsWith("{") || !update.endsWith("}")) return update;
  const fields = new Map(parseSnbtCompound(current).map((field) => [field.name, field.value]));
  for (const field of parseSnbtCompound(update)) {
    const previous = fields.get(field.name);
    fields.set(field.name, previous ? mergeSnbtValue(previous, field.value) : field.value);
  }
  return serializeSnbtCompound(fields);
}

function readMatrix(raw: string | null, label: string): Matrix16 {
  if (!raw?.startsWith("[") || !raw.endsWith("]")) throw new Error(`${label} must be an SNBT list.`);
  return asMatrix16(splitSnbtTopLevel(raw.slice(1, -1)).map((value) => {
    const parsed = Number(value.replace(/[bBsSlLfFdD]$/, ""));
    if (!Number.isFinite(parsed)) throw new Error(`${label} contains an invalid number: ${value}`);
    return parsed;
  }), label);
}

function readStringList(raw: string | null): string[] {
  if (!raw?.startsWith("[") || !raw.endsWith("]")) return [];
  return splitSnbtTopLevel(raw.slice(1, -1)).flatMap((value) => {
    try {
      const parsed = JSON.parse(value) as unknown;
      return typeof parsed === "string" ? [parsed] : [];
    } catch {
      return value.startsWith("'") && value.endsWith("'") ? [value.slice(1, -1)] : [];
    }
  });
}

function readBareField(compound: string, name: string): string | null {
  const raw = readSnbtRawField(compound, name);
  return raw && /^[A-Za-z0-9._+-]+$/.test(raw) ? raw : null;
}

function readSnbtString(raw: string): string | null {
  if (raw.startsWith('"') && raw.endsWith('"')) {
    try {
      const value = JSON.parse(raw) as unknown;
      return typeof value === "string" ? value : null;
    } catch {
      return null;
    }
  }
  return raw.startsWith("'") && raw.endsWith("'") ? raw.slice(1, -1) : null;
}

function readIntegerField(compound: string, name: string, fallback: number): number {
  const raw = readSnbtRawField(compound, name);
  if (raw == null) return fallback;
  const value = Number(raw.replace(/[bBsSlL]$/, ""));
  if (!Number.isInteger(value) || value < 0) throw new Error(`${name} must be a non-negative integer.`);
  return value;
}

function parseText(value: string): unknown {
  try { return JSON.parse(value) as unknown; } catch { return { text: value }; }
}

function prettify(value: string): string {
  return value.replaceAll("_", " ").replace(/\b\w/g, (character) => character.toUpperCase());
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
